# -*- coding: utf-8 -*-
"""Analise e modelo preditivo Preço Aluguel SP_2019.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17R2ZT1N2jRQyAHlJsLKXP56h9z8d2z0l

# Analise de Dados: Preço de Aluguel em SP

## Carregamento dos Dados

Os dados foram carregados diretamente de um arquivo CSV que se encontra no Google Driver
"""

# Importar bibliotecas necessárias
import shap
import pandas as pd
import numpy as np
import seaborn as sns
import numpy as np
from scipy.stats import entropy
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import KFold, train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE
from sklearn.model_selection import GridSearchCV

#Carregando os dados
base = pd.read_csv('/content/drive/MyDrive/Regressao_Linear/sao-paulo-properties-april-2019.csv')

#Guardando as informações sobre residencias que estejam somente para locação
dados = base[base['Negotiation Type'] == 'rent']

#Criando uma nova coluna somente com as regiões
dados[['District', 'City']] = dados['District'].str.split('/', expand=True)

#Deletando as colunas que não irao fazer parte da analise e modelo
dados = dados.drop(['New','City', 'Property Type', 'Negotiation Type', 'Latitude','Longitude'], axis=1)

#Verificar valores ausentes
print(dados.isnull().sum())

#Verificar as primeiras linhas dos dados
dados.head()

"""## Descrição dos Dados

Os dados incluem as seguintes variáveis



* **Price**: Preço final anunciado (R$ Real Brasileiro)
* **Condo**: Despesas de condominio
* **Size**: O tamanho da propriedade em metros quadrados m² (somente áreas privadas)
* **Rooms**: Numero de quartos
* **Toilets**: Número de banheiros (todos os banheiros)
* **Suites**: Número de quartos com casa de banho privativa
* **Parking**: Número de vagas de estacionamento
* **Elevator**: Elevador no prédio (1 = Sim, 0 = Não)
* **Furnished**: Propriedade imobiliada/financiada (1 = Sim, 0 = Não)
* **Swimming Pool**: Imovél com piscina (1 = Sim, 0 = Não)

## Estatisticas Descritivas

Vamos agora verificar algumas estatísticas descritivas dos dados
"""

#Estatisticas gerais do conjunto de dados
dados.describe()

"""## Análise de Distribuicoes

A seguir, graficos das ditribuições dos atributos numericos e categóricos
"""

#Variáveis numéricas
var_num = ['Price','Condo','Size','Rooms','Toilets','Suites','Parking']

#Variaveis Categoricas
var_cat = ['Elevator','Furnished','Swimming Pool']

#Plotar distribuicoes numericas

fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(12, 12))

for i, col in enumerate(var_num):
    ax = axes[i//2, i%2]
    ax.hist(dados[col], bins=10, color='blue',edgecolor='black')
    ax.set_title(f'Distribuição de {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Frequência')

fig.delaxes(axes[3,1])
plt.tight_layout()
plt.show()

#A variavel alvo 'Price', visualizando pelo os graficos, esta com a distribuição assimetrica. Devido a isso vamos criar uma nova variavel com logatimo, para melhor trabalhar no modelo preditivo
dados['log_Price'] = np.log(dados['Price'])

#Plotar distribuicoes numericas

fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(12, 12))

for i, col in enumerate(var_cat):
    ax = axes[i//2,i%2]
    dados[col].value_counts().plot(kind='bar', ax=ax, color='red', edgecolor='black')
    ax.set_title(f'Distribuição de {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Frequência')

fig.delaxes(axes[1,1])
fig.delaxes(axes[2,0])
fig.delaxes(axes[2,1])
plt.tight_layout()
plt.show()

"""## Análise Exploratoria

**Mostrando a quantidade de residencias por bairro/distrito**
"""

#Calculando quantidade de distritos
frequencia_bairros = dados['District'].value_counts()

#Criando uma datafram com a frequencia dos bairros
tabela_qtd_bairros = pd.DataFrame({
    'Bairro': frequencia_bairros.index,
    'Quantidade': frequencia_bairros.values})

#Exibindo a dataframe
tabela_qtd_bairros.set_index('Bairro', inplace=True)
tabela_qtd_bairros

"""**Média de valores de preço de aluguel por bairro**"""

#Calculando a media de alguel por bairro
media_bairro = dados.groupby(['District']).agg({'Price': 'mean'}).reset_index().sort_values('Price', ascending=False)

#Criando um dataframe com a media de preço de aluguel por bairro
tabela_media_bairro = pd.DataFrame({
    'Bairro': media_bairro['District'],
    'Media_Preco': media_bairro['Price'].round(2)})

#Exibindo a dataframe
tabela_media_bairro.set_index('Bairro', inplace=True)
tabela_media_bairro

"""**Plotando um grafico mostrando os indices dos bairros com valores de alguel mais altos e mais baixos**"""

#Duas variaveis, cada uma guarda os bairros com o valores mais altos e mais baixos

bairros_mais_caros = tabela_media_bairro.nlargest(5, 'Media_Preco')
bairros_mais_baratos = tabela_media_bairro.nsmallest(5, 'Media_Preco')

plt.scatter(bairros_mais_caros.index, bairros_mais_caros['Media_Preco'], color='red', label='Mais Caros')

plt.scatter(bairros_mais_baratos.index, bairros_mais_baratos['Media_Preco'], color='blue', label='Mais Baratos')

#Exibindo o grafico
plt.title('Distribuição dos 5 Bairros com Preço de Aluguel Mais Caros e Mais Baratos')
plt.xlabel('Bairro')
plt.xticks(rotation=45)
plt.ylabel('Preço de Aluguel')
plt.legend()
plt.show()

"""**Correlação entre características dos Imóveis e Preço de Aluguel**"""

#Selecionando as variaveis para analisar na correlação
dados_cor = dados[['log_Price','Price','Condo','Size','Rooms','Toilets','Suites','Parking','Elevator','Furnished','Swimming Pool']]

#Criando a correlação entre as variaveis
correlacao = dados_cor.corr()

#Visualizando a correlação e o grafico
sns.heatmap(correlacao, annot=True)
correlacao

"""## Preparação dos Dados para Modelagem"""

#Separar variáveis preditoras (x) e alvo (y)
x = dados[['Condo','Size','Rooms','Toilets','Suites','Parking','Elevator','Furnished','Swimming Pool']]
y = dados['log_Price']

#Dividir os dados em treino e teste (80% treino, 20% teste)
x_treino_1, x_teste_1, y_treino_1,y_teste_1 = train_test_split(x,y, test_size=0.2, random_state=42)

"""## Treinamento de Modelos Preditivos

---


**Primeiro modelo**

> Random Forest Regressor
"""

#Treinar o modelo de Regressão Linear usando Random Forest Regressor
modelo_1 = RandomForestRegressor()
modelo_1.fit(x_treino_1, y_treino_1)

#Capturando as variaveis mais "importantes" que foram usadas na criação da arvore de decisão
importancia = modelo_1.feature_importances_
variaveis = list(zip(['Condo','Size','Rooms','Toilets','Suites','Parking','Elevator','Furnished','Swimming Pool'], importancia))
variaveis_ordenadas = sorted(variaveis, key=lambda x: x[1], reverse=True)
for coluna, importancia in variaveis_ordenadas:
    print(f"{coluna}: {importancia.round(3)}")

#O SHAP esta sendo mostrado para verificar como cada atributo afeta para o resultado do modelo
expln = shap.TreeExplainer(modelo_1)
shap_values = expln.shap_values(x_teste_1)
shap.summary_plot(shap_values, x_teste_1)

k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

#Método (RFE) para selecionar as melhores features (variaves independentes/atributos)
rfg = RandomForestRegressor(random_state=42)
parametros = {'n_features_to_select': range(1, x.shape[1] + 1)}
rfe = RFE(rfg)

#Treinamento do modelo k vezes, testando todas as combinações possiveis de valores, calculando a performance média do modelo em cada combinação
grid = GridSearchCV(rfe, parametros, cv=kf, scoring='r2')
grid.fit(x, y)

#Mostrando em tela a quantidade certa de variaveis para o nosso modelo
print("Melhor número de variáveis:", grid.best_params_['n_features_to_select'])

#Visualizando as melhores variaveis para o nosso modelo.
for i,col in zip(range(x.shape[1]), x.columns):
  print(f"{col} selected={grid.best_estimator_.support_[i]} rank={grid.best_estimator_.ranking_[i]}") # Access support_ and ranking_ from grid.best_estimator_

#Obtendo o Coeficiente de Determinação do nosso primeiro modelo
print(f"R²: {modelo_1.score(x_treino_1, y_treino_1)}")

"""**Devido ao coeficiente de determinação (R²) estar muito alto, é provável que o nosso primeiro modelo esteja enfrentando problemas de generalização, apresentando um ajuste excessivo aos dados de teste (overfitting). Para verificar a capacidade de generalização do modelo, utilizaremos a técnica de validação cruzada (KFold)**"""

#Exibição de cada coeficiente do teste e a media
scores = cross_val_score(modelo_1, x, y, cv=kf, scoring='r2')
print(f"R² Score for each fold: {[round(score, 4) for score in scores]}")
print(f"Média R² total: {scores.mean()}")

"""---


**Segundo modelo**

> Random Forest Regressor

**O segundo modelo está sendo desenvolvido com base em toda a análise e nos testes realizados no primeiro modelo, utilizando as variáveis que mais influenciam a variável alvo.**
"""

x = dados[['Condo','Size','Rooms','Suites','Parking','Furnished','Swimming Pool']]

x_treino_2, x_teste_2, y_treino_2,y_teste_2 = train_test_split(x,y, test_size=0.20, random_state=42)

modelo_2 = RandomForestRegressor()
modelo_2.fit(x_treino_2, y_treino_2)

#Obtendo o Coeficiente de Determinação do nosso primeiro modelo
round(modelo_2.score(x_treino_2, y_treino_2),3)

"""**Devido ao coeficiente de determinação (R²) estar muito alto, é provável que o nosso segundo modelo esteja tambem enfrentando problemas de sobreajuste. E para verificar a capacidade de generalização do modelo, utilizaremos a técnica de validação cruzada (KFold)**"""

#Exibição de cada coeficiente do teste e a media
scores_2 = cross_val_score(modelo_2, x, y, cv=kf, scoring='r2')
print(f"R² Score for each fold: {[round(score, 4) for score in scores_2]}")
print(f"Média R² total: {scores_2.mean()}")

"""## Teste de predição e visualização de desempenho dos modelos"""

#Capturando a performance de teste de cada modelo, predição.
pred_modelo_1 = modelo_1.predict(x_teste_1)
pred_modelo_2 = modelo_2.predict(x_teste_2)

#Visualizando os erros de previsão de cada modelo
print('Primeiro modelo')
print(f"MAE: {mean_absolute_error(y_teste_1, pred_modelo_1)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_teste_1, pred_modelo_1))}")
print('-------------------------')
print('Segundo modelo')
print(f"MAE: {mean_absolute_error(y_teste_2, pred_modelo_2)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_teste_2, pred_modelo_2))}")

"""**Abaixo um comparativo entre a previsão de cada modelo com a variavel alvo real**"""

#Plotando o comparativo entre o previsto e o resultado real do primeiro modelo
ax = sns.scatterplot(x = pred_modelo_1, y = y_teste_1)
ax.figure.set_size_inches(12, 6)
ax.set_title('Primeiro Modelo - Previsto X Real', fontsize=18)
ax.set_xlabel('Real', fontsize=14)
ax.set_ylabel('Previsto', fontsize=14)
ax

#Plotando o comparativo entre o previsto e o resultado real do segundo modelo
ax = sns.scatterplot(x = pred_modelo_2, y = y_teste_2)
ax.figure.set_size_inches(12, 6)
ax.set_title('Segundo Modelo - Previsto X Real', fontsize=18)
ax.set_xlabel('Real', fontsize=14)
ax.set_ylabel('Previsto', fontsize=14)
ax

"""### Conclusão
Comparamos os dois modelos preditivos para estimar o preço do aluguel com base nas informações fornecidas. A partir da avaliação apresentada acima, podemos determinar qual modelo apresenta o melhor desempenho.

crédito: https://www.kaggle.com/datasets/argonalyst/sao-paulo-real-estate-sale-rent-april-2019
"""