# -*- coding: utf-8 -*-
"""Análise de Dados e Modelo Preditivo: Naufragio Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12irCRMV0mDlsgcRhBZo-oYee5E-8nHcE

# Análise de Dados e Modelo Preditivo: Naufragio Titanic

## Carregamento dos Dados

Os dados foram carregados diretamente de um arquivo CSV que se encontra no Google Driver
"""

#Importando bibliotecas necessarias
import shap
import pandas as pd
import numpy as np
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy.stats import entropy
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score, confusion_matrix, classification_report # Added classification_report import here
from sklearn.model_selection import KFold, train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import GridSearchCV

#Carregando os dados
dados = pd.read_csv('/content/drive/MyDrive/machine_learning/titanic (1).csv')

#Verificar valores ausentes
print(dados.isnull().sum())

#Verificar as primeiras linhas dos dados
dados.head()

"""## Descrição dos dados

Os dados incluem a seguintes variaveis

  * **Survived:** Sobrevivência
  * **Pclass**: Classe da passagem (Status socioeconomico)
  * **Name:** Nome do passageiro
  * **Sex:** Sexo (male = Masculino, female= Feminino)
  * **Age:** Idade do passageiro (Idade fracionada se for menor que 1. Estimada, no formato xx,5)
  * **Siblings/Spouses Aboard:** Contagem de relaçoes familiares (irmão(ã) ou conjugue)
  * **Parents/Children Aboard:** Contagem de relação paterna ou materna (mãe, pai, filho(a))
  * **Fare:** Tarifa do passageiro

## Estatisticas Descritivas
"""

#Estatisticas gerais do conjunto de dados
dados.describe()

"""## Análise de Distribuições

A seguir, graficos das distribuições dos atributos numericos e categoricos
"""

#Variáveis numéricas
var_num = ['Age', 'Fare', 'Siblings/Spouses Aboard', 'Parents/Children Aboard']

#Variaveis Categoricas
var_cat = ['Survived', 'Pclass', 'Sex']

#Criando uma função para receber as variaveis e plotar os graficos
def plotar_hist(variaveis, fig, axes):
  for i, col in enumerate(variaveis):
    ax = axes[i//2,i%2]

    if(variaveis[col].dtype == 'object' or variaveis[col].nunique() < 4):

      variaveis[col].value_counts().plot(kind='bar', ax=ax, color='blue', edgecolor='black')
      ax.set_title(f'Distribuição de {col}')
      ax.set_ylabel('Frequência')
    else:
      ax.hist(variaveis[col], bins=10, color='red', edgecolor='black', )
      ax.set_title(f'Distribuição de {col}')
      ax.set_ylabel('Frequência')

plt.tight_layout()
plt.show()

#Plotar distribuicoes numericas
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(16, 12))

plotar_hist(dados[var_num], fig, axes)

#Plotar distribuicoes categoricas
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(16, 12))

plotar_hist(dados[var_cat], fig, axes)

"""## Análise Exploratoria"""

# @title Criando a estrutura para a tabela/grafico de distribuição de sobreviventes/mortos
#Coletando a frequencia de mortes por sexo e em percentual
frequencia_mortes_sexo = pd.crosstab(dados['Sex'], dados['Survived'], margins=True, margins_name="Total")
frequencia_mortes_sexo_sem_total = frequencia_mortes_sexo.iloc[:-1, :-1]
frequencia_mortes_sexo_perc = pd.crosstab(dados['Sex'], dados['Survived'], normalize=True, margins=True, margins_name="Total %") * 100
frequencia_mortes_sexo_perc_sem_total = frequencia_mortes_sexo_perc.iloc[:-1, :-1]

#Separando a frequencias por sexo em variaveis
mulher_obito = frequencia_mortes_sexo.loc['female'][0]
homem_obito = frequencia_mortes_sexo.loc['male'][0]

mulher_sob =  frequencia_mortes_sexo.loc['female'][1]
homem_sob = frequencia_mortes_sexo.loc['male'][1]

mortos_mulheres = round((mulher_obito / (mulher_obito + mulher_sob)) *100, 2)
mortos_homens = round((homem_obito / (homem_obito + homem_sob)) *100, 2)

sobrev_mulheres = round((mulher_sob / (mulher_obito + mulher_sob)) *100,2)
sobrev_homens = round((homem_sob / (homem_obito + homem_sob)) *100,2)

mortos_por_sexo = [mortos_mulheres, mortos_homens]
sobrev_por_sexo = [sobrev_mulheres, sobrev_homens]

#Criando a estrutura para a tabela de sobreviventes
linha_total = {'Mortos': frequencia_mortes_sexo.loc['Total'][0],'Sobreviventes': frequencia_mortes_sexo.loc['Total'][1],'Mortos %': "-",'Sobreviventes %': "-", 'Total %': "-"}

frequencia_mortes_sexo_combinado = pd.concat([frequencia_mortes_sexo_sem_total, frequencia_mortes_sexo_perc_sem_total.round(2)], axis=1).astype('object')
frequencia_mortes_sexo_combinado['Total %'] = frequencia_mortes_sexo_perc['Total %'].round(2)
frequencia_mortes_sexo_combinado.columns = ['Mortos', 'Sobreviventes', 'Mortos %', 'Sobreviventes %','Total %']
frequencia_mortes_sexo_combinado["Mortos por sexo %"] = mortos_por_sexo
frequencia_mortes_sexo_combinado["Sobreviventes por sexo %"] = sobrev_por_sexo
frequencia_mortes_sexo_combinado.loc["Total", "Total"] = frequencia_mortes_sexo.loc["Total", "Total"]
frequencia_mortes_sexo_combinado["Total"] = frequencia_mortes_sexo["Total"].reindex(frequencia_mortes_sexo_combinado.index)
frequencia_mortes_sexo_combinado.index = ['Mulher', 'Homem','Total']

frequencia_mortes_sexo_combinado = frequencia_mortes_sexo_combinado.astype('object')

frequencia_mortes_sexo_combinado = frequencia_mortes_sexo_combinado[[
    "Mortos",
    "Sobreviventes",
    "Mortos por sexo %",
    "Sobreviventes por sexo %",
    "Mortos %",
    "Sobreviventes %",
    "Total",
    "Total %"
]]

#Adiciona a linha total na tabela
for coluna, valor in linha_total.items():
  frequencia_mortes_sexo_combinado.at['Total', coluna] = valor

frequencia_mortes_sexo_combinado.fillna("-", inplace=True)

#Dividindo passageiros com parentes e que não tem parentes
dados_com_parentes = dados[dados['Parents/Children Aboard'] > 0]
dados_sem_parentes = dados[dados['Parents/Children Aboard'] == 0]

#Plotando os graficos de distribuição de sobreviventes/mortos
fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 10))
cores = ['red','navy']
font = {'color':'white','fontsize':11, 'weight':'bold'}


ax = axes[0]

ax.pie(dados['Survived'].value_counts(), labels=['Mortos', 'Sobreviventes'], autopct='%1.1f%%', colors=cores, textprops=font)
ax.set_title('Distribuição de Mortos / Sobreviventes', fontsize=12)

ax = axes[1]

ax.pie(dados_com_parentes['Survived'].value_counts(), labels=['Mortos', 'Sobreviventes'], autopct='%1.1f%%',colors=cores, textprops=font)
ax.set_title('Distribuição de Mortos / Sobreviventes com parentesco',fontsize=12)

ax = axes[2]

ax.pie(dados_sem_parentes['Survived'].value_counts(), labels=['Mortos', 'Sobreviventes'], autopct='%1.1f%%',colors=cores, textprops=font)
ax.set_title('Distribuição de Mortos / Sobreviventes sem parentesco', fontsize=12)

plt.show()

#Visualizando a tabela de distribuição de sobreviventes/mortos
frequencia_mortes_sexo_combinado

# @title Criando a estrutura para a tabela/grafico de distribuição de sobreviventes/mortos por classe e sexo
#Coletando os dados dos passageiros, sobreviventes e mortos por classe e sexo
mortes_p1_m = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 1) & (dados['Sex'] == 'male')].shape[0]
mortes_p2_m = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 2) & (dados['Sex'] == 'male')].shape[0]
mortes_p3_m = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 3) & (dados['Sex'] == 'male')].shape[0]

mortes_p1_f = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 1) & (dados['Sex'] == 'female')].shape[0]
mortes_p2_f = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 2) & (dados['Sex'] == 'female')].shape[0]
mortes_p3_f = dados[(dados['Survived'] == 0) & (dados['Pclass'] == 3) & (dados['Sex'] == 'female')].shape[0]

sobreviventes_p1_m = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 1) & (dados['Sex'] == 'male')].shape[0]
sobreviventes_p2_m = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 2) & (dados['Sex'] == 'male')].shape[0]
sobreviventes_p3_m = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 3) & (dados['Sex'] == 'male')].shape[0]

sobreviventes_p1_f = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 1) & (dados['Sex'] == 'female')].shape[0]
sobreviventes_p2_f = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 2) & (dados['Sex'] == 'female')].shape[0]
sobreviventes_p3_f = dados[(dados['Survived'] == 1) & (dados['Pclass'] == 3) & (dados['Sex'] == 'female')].shape[0]

classes = sorted(dados['Pclass'].unique())
str_classes = [str(n) for n in classes]
mortes_m = [mortes_p1_m, mortes_p2_m, mortes_p3_m]
mortes_f = [mortes_p1_f, mortes_p2_f, mortes_p3_f]
sobreviventes_m = [sobreviventes_p1_m, sobreviventes_p2_m, sobreviventes_p3_m]
sobreviventes_f = [sobreviventes_p1_f, sobreviventes_p2_f, sobreviventes_p3_f]

#Criando tabela de classe por sobreviventes/mortos
frequencia_mortes_classe = pd.crosstab(dados['Pclass'], dados['Survived'], margins=True, margins_name="Total")
frequencia_mortes_classe_sem_total = frequencia_mortes_classe.iloc[:-1, :-1]

#Criando tabela de classe por sobreviventes/mortos em percentual
frequencia_mortes_classe_perc = pd.crosstab(dados['Pclass'], dados['Survived'], normalize=True, margins=True, margins_name="Total %") * 100
frequencia_mortes_classe_perc_sem_total = frequencia_mortes_classe_perc.iloc[:-1, :-1]

nova_linha = {'Mortos': frequencia_mortes_classe.loc['Total'][0],'Sobreviventes': frequencia_mortes_classe.loc['Total'][1],'Mortos %': "-",'Sobreviventes %': "-", 'Total %': "-"}

#Separando a frequencias por classe em variaveis
classe1_obito = frequencia_mortes_classe.loc[1][0]
classe2_obito = frequencia_mortes_classe.loc[2][0]
classe3_obito = frequencia_mortes_classe.loc[3][0]

classe1_sob = frequencia_mortes_classe.loc[1][1]
classe2_sob = frequencia_mortes_classe.loc[2][1]
classe3_sob = frequencia_mortes_classe.loc[3][1]

mortos_por_classe1 = round((classe1_obito / (classe1_obito + classe1_sob)) *100, 2)
mortos_por_classe2 = round((classe2_obito / (classe2_obito + classe2_sob)) *100, 2)
mortos_por_classe3 = round((classe3_obito / (classe3_obito + classe3_sob)) *100, 2)

sob_por_classe1 = round((classe1_sob / (classe1_obito + classe1_sob)) *100,2)
sob_por_classe2 = round((classe2_sob / (classe2_obito + classe2_sob)) *100,2)
sob_por_classe3 = round((classe3_sob / (classe3_obito + classe3_sob)) *100,2)

mortos_por_classe = [mortos_por_classe1, mortos_por_classe2, mortos_por_classe3]
sobrev_por_classe = [sob_por_classe1, sob_por_classe2, sob_por_classe3]

#Criando a estrutura para a tabela de distribuição de sobreviventes/mortos por classe e sexo
frequencia_mortes_classe_perc_combinado = pd.concat([frequencia_mortes_classe_sem_total, frequencia_mortes_classe_perc_sem_total.round(2)], axis=1).astype('object')
frequencia_mortes_classe_perc_combinado['Total %'] = frequencia_mortes_classe_perc['Total %'].round(2)
frequencia_mortes_classe_perc_combinado.columns = ['Mortos', 'Sobreviventes', 'Mortos %', 'Sobreviventes %', "Total %"]
frequencia_mortes_classe_perc_combinado["Mortos por classe %"] = mortos_por_classe
frequencia_mortes_classe_perc_combinado["Sobreviventes por classe %"] = sobrev_por_classe
frequencia_mortes_classe_perc_combinado.loc["Total", "Total"] = frequencia_mortes_classe.loc["Total", "Total"]
frequencia_mortes_classe_perc_combinado["Total"] = frequencia_mortes_classe["Total"].reindex(frequencia_mortes_classe_perc_combinado.index)
frequencia_mortes_classe_perc_combinado.index = ['Classe 1', 'Classe 2', 'Classe 3', 'Total']

frequencia_mortes_classe_perc_combinado = frequencia_mortes_classe_perc_combinado.astype('object')

#Adicionando a linha total a tabela
for coluna, valor in nova_linha.items():
  frequencia_mortes_classe_perc_combinado.at['Total', coluna] = valor

frequencia_mortes_classe_perc_combinado = frequencia_mortes_classe_perc_combinado[[
    "Mortos",
    "Sobreviventes",
    "Mortos por classe %",
    "Sobreviventes por classe %",
    "Mortos %",
    "Sobreviventes %",
    "Total",
    "Total %"
]]
frequencia_mortes_classe_perc_combinado.fillna("-", inplace=True)
frequencia_mortes_classe_perc_combinado.index.name = 'Classe'

#Plotar grafico de distribuição de sobreviventes/mortos por classe e sexo
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(12, 5))

ax = axes[0]

ax.bar(str_classes, mortes_m, label='Homens', color=cores[0])
ax.bar(str_classes, mortes_f, bottom=mortes_m ,label='Mulheres', color='#FF9999')
ax.set_xlabel('Classe')
ax.set_ylabel('Número de Mortes')
ax.set_title('Distribuição de Mortes por Classe e Sexo')
ax.legend()

ax = axes[1]

ax.bar(str_classes, sobreviventes_m, label='Homens', color=cores[1])
ax.bar(str_classes, sobreviventes_f, bottom=sobreviventes_m ,label='Mulheres',color='#344CB7')
ax.set_xlabel('Classe')
ax.set_ylabel('Número de Sobreviventes')
ax.set_title('Distribuição de Sobreviventes por Classe e Sexo')
ax.legend()

plt.tight_layout()
plt.show()

#Visualizando tabela de distribuição de sobreviventes/mortos por classe e sexo
frequencia_mortes_classe_perc_combinado

# @title Criando a estrutura para tabela/grafico de distribuição de mortos por faixa etaria

#Criando as classes para faixa de etaria
classes = [0,10,20,30,40,50,60,70,80]

#Descrição de cada faixa
labels = [
    'Abaixo de 10 anos',
    'Entre 10 e 20 anos',
    'Entre 20 e 30 anos',
    'Entre 30 e 40 anos',
    'Entre 40 e 50 anos',
    'Entre 50 e 60 anos',
    'Entre 60 e 70 anos',
    'Acima de 70 anos'
]

#Frequencia de sobreviventes por idade
faixa_etaria_sobrev = pd.value_counts (pd.cut(x=dados[dados['Survived'] == 1]['Age'],
                        bins=classes,
                        labels=labels,
                        include_lowest=True))

#Frequencia de mortos por idade
faixa_etaria_obito = pd.value_counts (pd.cut(x=dados[dados['Survived'] == 0]['Age'],
                        bins=classes,
                        labels=labels,
                        include_lowest=True))

#Porcentagem de sobreviventes e mortos
mortos_norm = round(faixa_etaria_obito / faixa_etaria_obito.sum() * 100,2)
vivos_norm = round(faixa_etaria_sobrev / faixa_etaria_sobrev.sum() * 100,2)

#Porcentagem de sobreviventes e mortos por faixa etaria
mortos_por_faixa = round((faixa_etaria_obito / (faixa_etaria_obito + faixa_etaria_sobrev)) *100, 2)
sobrev_por_faixa = round((faixa_etaria_sobrev / (faixa_etaria_obito + faixa_etaria_sobrev)) *100, 2)

#Criando a estrutura para a tabela de distribuição de sobreviventes/mortos por faixa etaria
dist_freq_vivos_mortos_etaria = pd.DataFrame({'Mortos': faixa_etaria_obito, 'Sobreviventes': faixa_etaria_sobrev, 'Mortos por faixa %': mortos_por_faixa, 'Sobreviventes por faixa %': sobrev_por_faixa ,'Mortos %': mortos_norm, 'Sobreviventes %':vivos_norm, 'Total': faixa_etaria_obito + faixa_etaria_sobrev, 'Total %': round(mortos_norm + vivos_norm,2)})
total_linha = {'Mortos': faixa_etaria_obito.sum(), 'Sobreviventes': faixa_etaria_sobrev.sum(), 'Mortos por faixa %': "-", 'Sobreviventes por faixa %': "-", 'Mortos %': "-", 'Sobreviventes %': "-", 'Total':  faixa_etaria_obito.sum() + faixa_etaria_sobrev.sum(), 'Total %':"-"}
dist_freq_vivos_mortos_etaria.sort_index(inplace=True)
dist_freq_vivos_mortos_etaria.loc['Total'] = total_linha
dist_freq_vivos_mortos_etaria.index.name = 'Faixa Etária'

#Plotar grafico de distribuição de sobreviventes/mortos por faixa etaria
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(12, 5))
dados_sem_total = dist_freq_vivos_mortos_etaria.loc[dist_freq_vivos_mortos_etaria.index != 'Total']


ax = axes[0]

ax.barh(dados_sem_total.index, dados_sem_total['Mortos'], color=cores[0])
ax.set_xlabel('Número de Mortos')
ax.set_ylabel('Faixa Etária')
ax.set_title('Distribuição de Mortos por Faixa Etária')
ax.invert_yaxis()

ax = axes[1]

ax.barh(dados_sem_total.index, dados_sem_total['Sobreviventes'], color=cores[1])
ax.set_xlabel('Número de Sobreviventes')
ax.set_ylabel('Faixa Etária')
ax.set_title('Distribuição de Sobreviventes por Faixa Etária')
ax.invert_yaxis()


plt.tight_layout()
plt.show()

#Visualizar tabela de distribuição de sobreviventes/mortos por faixa etaria
dist_freq_vivos_mortos_etaria

#Converter variáveis categóricas para numéricas
label_encoder = LabelEncoder()

for coluna in ['Pclass','Sex']:
  dados[coluna] = label_encoder.fit_transform(dados[coluna])

#Selecionando as variaveis para analisar na correlação
dados_cor = dados[['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Siblings/Spouses Aboard', 'Parents/Children Aboard']]

#Criando a correlação entre as variaveis
correlacao = dados_cor.corr()

#Visualizando a correlação e o grafico
sns.heatmap(correlacao, annot=True, cmap='Blues')
correlacao

"""## Preparação dos dados para modelagem"""

#Separar variáveis preditoras (x) e alvo (y)
X = dados[['Pclass', 'Sex', 'Age', 'Fare', 'Siblings/Spouses Aboard', 'Parents/Children Aboard']]
y = dados['Survived']

#Dividir os dados em treino e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""## Treinamento de modelos preditivos"""

desempenhos = {}

"""

---


**Primeiro modelo**

> Decision Tree Classifier"""

#Treinar o modelo usando Decision Tree Classifier
modelo_1 = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)
modelo_1.fit(X_train,y_train)

#Capturando as variaveis mais "importantes" que foram usadas na criação da arvore de decisão
importancia = modelo_1.feature_importances_
variaveis = list(zip(X.columns, importancia))
variaveis.sort(key=lambda x: x[1], reverse=True)

for coluna, importancia in variaveis:
  print(f'{coluna}: {importancia}')

k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

#Método (RFE) para selecionar as melhores features (variaves independentes/atributos)
parametros = {'n_features_to_select': range(1, X.shape[1] + 1)}
rfe = RFE(modelo_1)

#Treinamento do modelo k vezes, testando todas as combinações possiveis de valores, calculando a performance média do modelo em cada combinação
grid = GridSearchCV(rfe, parametros, cv=kf)
grid.fit(X, y)

#Mostrando em tela a quantidade certa de variaveis para o nosso modelo
print("Melhor numero de variaveis: ", grid.best_params_['n_features_to_select'])

#Visualizando as melhores variaveis para o nosso modelo.
for i, coluna in zip(range(X.shape[1]), X.columns):
  print(f'{coluna} selecionado={grid.best_estimator_.support_[i]} posição={grid.best_estimator_.ranking_[i]}')

#Previsão do modelo 1
previsao_modelo_1 = modelo_1.predict(X_test)

#Avaliação do modelo 1
print(accuracy_score(y_test, previsao_modelo_1))

desempenhos['Decision Tree Classifier'] = accuracy_score(y_test, previsao_modelo_1)

"""

---


**Segundo modelo**

> Logistic Regression"""

#Usando somente os atributos que foram selecionados acima na visualização das melhores 'features'
X = dados[['Pclass', 'Sex', 'Age', 'Fare','Siblings/Spouses Aboard']]
y = dados['Survived']

#Dividir os dados em treino e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Treinar o modelo usando Logistic Regression
modelo_2 = LogisticRegression()
modelo_2.fit(X_train,y_train)

#Previsão do modelo 2
previsao_modelo_2 = modelo_2.predict(X_test)

#Avaliação do modelo 2
print(accuracy_score(y_test, previsao_modelo_2))

desempenhos['Logistic Regression'] = accuracy_score(y_test, previsao_modelo_2)

"""

---


**Terceiro modelo**

> KNeighborsClassifier"""

#Devido a toda a analise exploratoria, usaremos aqui somente os atributos que possui muito impacto para sobrevivencia ou não do passageiro
X = dados[['Pclass', 'Sex', 'Age']]
y = dados['Survived']

#Dividir os dados em treino e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Vamos estabelecer e testar qual o melhor valor de k, para usarmos em nosso modelo.
valores = {}
k = 1
vencedor = []

#Treinar o modelo usando KNeighborsClassifier
while k <= 25:
  modelo_3 = KNeighborsClassifier(n_neighbors=k)
  modelo_3.fit(X_train, y_train)
  previsao_modelo_3 = modelo_3.predict(X_test)
  acertos_knn = accuracy_score(y_test, previsao_modelo_3)
  valores[k] = round(acertos_knn,4)
  k += 1

#Visualização do melhor valor de k e o melhor desempenho do modelo
print(valores)
valor_k = max(valores, key=valores.get)
print("Valor do k é ",valor_k," e porcentagem de acertos",valores[valor_k])

desempenhos['KNeighborsClassifier'] = valores[valor_k]

"""## Visualização dos desempenho dos modelos"""

print("Matriz de Confusão - Decision Tree Classifier")
print(confusion_matrix(y_test, previsao_modelo_1))
print("\nRelatório de Classificação - Decision Tree Classifier")
print(classification_report(y_test, previsao_modelo_1))

print('\n')

print("Matriz de Confusão - Logistic Regression")
print(confusion_matrix(y_test, previsao_modelo_2))
print("\nRelatório de Classificação - Logistic Regression	")
print(classification_report(y_test, previsao_modelo_2))

print('\n')

print("Matriz de Confusão - KNeighborsClassifier")
print(confusion_matrix(y_test, previsao_modelo_3))
print("\nRelatório de Classificação - KNeighborsClassifier	")
print(classification_report(y_test, previsao_modelo_3))

result_modelos = pd.DataFrame.from_dict(desempenhos, orient='index', columns=['Acurácia'])
result_modelos.sort_values(by='Acurácia', ascending=False, inplace=True)
result_modelos.round(4)

"""### Conclusão
Analisando os resultados dos três modelos preditivos para estimar a sobrevivência dos passageiros no naufrágio do Titanic, é possível, com base nas métricas de avaliação apresentadas, identificar qual modelo demonstrou o melhor desempenho.

Crédito: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/problem12.html
"""